#! name= 𝗔𝗹𝗹 𝗜𝗻 𝗢𝗻𝗲
#! desc= 𝗯𝘆 𝗡𝗵𝗮 𝗔𝗻 𝗣𝗮 𝗧𝗲


[General]
bypass-system = true
skip-proxy = *.local, *.crashlytics.com
tun-excluded-routes = 192.168.0.0/16, 10.0.0.0/8, 172.16.0.0/12

[Header Rewrite]
^https:\/\/api\.(picsart|meiease)\.c(n|om)\/users\/show\/me\.json header-del if-none-match

[URL Rewrite]
(^https?:\/\/[\w-]+\.googlevideo\.com\/(?!dclk_video_ads).+?)&ctier=L(&.+?),ctier,(.+) $1$2$3 302
^https?:\/\/[\w-]+\.googlevideo\.com\/(?!(dclk_video_ads|videoplayback\?)).+&oad _ reject-200
^https?:\/\/(www|s)\.youtube\.com\/api\/stats\/ads _ reject-200
^https?:\/\/(www|s)\.youtube\.com\/(pagead|ptracking) _ reject-200
^https?:\/\/s\.youtube\.com\/api\/stats\/qoe\?adcontext _ reject-200

[Rule]
AND,((DOMAIN-SUFFIX,googlevideo.com), (PROTOCOL,UDP)),REJECT
AND,((DOMAIN,youtubei.googleapis.com), (PROTOCOL,UDP)),REJECT


[MITM]
hostname = %APPEND% api.revenuecat.com, buy.itunes.apple.com, us-central1-alight-creative.cloudfunctions.net, ap*.intsig.net, photos.adobe.io, api.revenuecat.com, nicegram.cloud, api.revenuecat.com, buy.itunes.apple.com, api.picsart.com, api-mobile.soundcloud.com, spclient.wg.spotify.com, premium*.truecaller.com, api-sub.meitu.com, redirector*.googlevideo.com,*.googlevideo.com,www.youtube.com,s.youtube.com,youtubei.googleapis.com

[Script]
# 𝗔𝗹𝗶𝗴𝗵𝘁 𝗠𝗼𝘁𝗶𝗼𝗻
http-response https://us-central1-alight-creative.cloudfunctions.net/getAccountStatusAndLicenses script-path=https://raw.githubusercontent.com/nhaanpate/module/nhaanpate/alightmotion.js, requires-body=true, timeout=5

#************************************#

# 𝗖𝗮𝗺𝗦𝗰𝗮𝗻𝗻𝗲𝗿

Camscanner = requires-body=1,script-path=https://raw.githubusercontent.com/nhaanpate/module/nhaanpate/camscanner.js,type=http-response,pattern= https:\/\/(api|api-cs.*)\.intsig\.net\/purchase\/cs\/query_property\?

#************************************#

# 𝗟𝗶𝗴𝗵𝘁𝗿𝗼𝗼𝗺

LightRoom=type=http-response,pattern=^https:\/\/photos\.adobe\.io\/v2\/accounts*,requires-body=1, max-size=0,script-path=https://raw.githubusercontent.com/nhaanpate/module/nhaanpate/lightroom.js,script-update-interval=-1

#************************************#

# 𝗟𝗼𝗰𝗸𝗲𝘁 𝗚𝗼𝗹𝗱

revenuecat = type=http-response, pattern=^https:\/\/api\.revenuecat\.com\/.+\/(receipts$|subscribers\/[^/]+$), script-path=https://raw.githubusercontent.com/nhaanpate/module/nhaanpate/revenuecat.js, requires-body=true, max-size=-1, timeout=60

deleteHeader = type=http-request, pattern=^https:\/\/api\.revenuecat\.com\/.+\/(receipts|subscribers), script-path=https://raw.githubusercontent.com/nhaanpate/module/nhaanpate/deleteheader.js, timeout=60

#************************************#

# 𝗡𝗶𝗰𝗲𝗚𝗿𝗮𝗺

Nicegram = type=http-response,pattern=^https?:\/\/(nicegram\.cloud\/api\/v\d\/user\/info|restore-access\.indream\.app\/restoreAccess),requires-body=1,max-size=0,script-path=https://raw.githubusercontent.com/nhaanpate/module/nhaanpate/nicegram.js,script-update-interval=0

#************************************#

# 𝗦𝗼𝘂𝗻𝗱𝗖𝗹𝗼𝘂𝗱 𝗚𝗼+

SoundCloudGo= type=http-response,pattern=https://api-mobile.soundcloud.com/configuration/ios,requires-body=1,script-path=https://raw.githubusercontent.com/nhaanpate/module/nhaanpate/soundcloud.js

#************************************#

# 𝗦𝗽𝗼𝘁𝗶𝗳𝘆

spotify-json = type=http-request,pattern=^https:\/\/spclient\.wg\.spotify\.com\/(artistview\/v1\/artist|album-entity-view\/v2\/album)\/,requires-body=0,script-path=https://raw.githubusercontent.com/nhaanpate/module/nhaanpate/spotify-json.js

spotify-proto = type=http-response,pattern=^https:\/\/spclient\.wg\.spotify\.com\/(bootstrap\/v1\/bootstrap|user-customization-service\/v1\/customize)$,requires-body=1,binary-mode=1,script-path=https://raw.githubusercontent.com/nhaanpate/module/nhaanpate/spotify-proto.js

#************************************#

# 𝗬𝗼𝘂𝗧𝘂𝗯𝗲

youtube.response = type=http-response,pattern=^https:\/\/youtubei\.googleapis\.com\/youtubei\/v1\/(browse|next|player|search|reel\/reel_watch_sequence|guide|account\/get_setting|get_watch),requires-body=1,max-size=-1,binary-body-mode=1,engine=default,script-path=https://raw.githubusercontent.com/nhaanpate/module/nhaanpate/youtube.js,argument="{}"

#************************************#

# 𝗣𝗶𝗰𝘀𝗮𝗿𝘁

http-request https://api.picsart.com/gw-v2/shop/subscription/apple/purchases script-path=https://raw.githubusercontent.com/nhaanpate/module/nhaanpate/picsart.js, requires-body=true, timeout=5

#************************************#

# 𝗧𝗿𝘂𝗲𝗖𝗮𝗹𝗹𝗲𝗿

Truecaller = type=http-response,pattern=^https://premium-(.+)\.truecaller\.com/v\d/(subscriptions|products\/apple),requires-body=1,max-size=0,script-path=https://raw.githubusercontent.com/nhaanpate/module/nhaanpate/truecaller.js

#************************************#

# 𝗪𝗶𝗻𝗸

Wink = type=http-response,pattern=^https:\/\/api-sub\.meitu\.com\/v\d\/user\/vip_info_by_group,requires-body=1,max-size=0,script-path=https://raw.githubusercontent.com/nhaanpate/module/nhaanpate/wink.js
