#!name= 𝗟𝗼𝗰𝗸𝗲𝘁 𝗚𝗼𝗹𝗱
#!desc= 𝗡𝗵𝗮 𝗔𝗻 𝗣𝗮 𝗧𝗲

[MITM]
hostname = %APPEND% api.revenuecat.com
[Script]
revenuecat = type=http-response, pattern=^https:\/\/api\.revenuecat\.com\/.+\/(receipts$|subscribers\/[^/]+$), script-path=https://raw.githubusercontent.com/nhaanpate/javascript/nhaanpate/revenuecat.js, requires-body=true, max-size=-1, timeout=60
deleteHeader = type=http-request, pattern=^https:\/\/api\.revenuecat\.com\/.+\/(receipts|subscribers), script-path=https://raw.githubusercontent.com/aleotoidayy/nghluan/aleoo/deleteheader.js, timeout=60
