#!name= 𝗣𝗶𝗰𝘀𝗮𝗿𝘁
#!desc= 𝗯𝘆 𝗡𝗵𝗮 𝗔𝗻 𝗣𝗮 𝗧𝗲

[Header Rewrite]
^https:\/\/api\.(picsart|meiease)\.c(n|om)\/users\/show\/me\.json header-del if-none-match

[MITM]
hostname = %APPEND% api.revenuecat.com, buy.itunes.apple.com, api.picsart.com

[Script]
http-request https://api.picsart.com/gw-v2/shop/subscription/apple/purchases script-path=https://raw.githubusercontent.com/nhaanpate/javascript/nhaanpate/picsartt.js, requires-body=true, timeout=5
