#!name= 𝗦𝗽𝗼𝘁𝗶𝗳𝘆
#!desc= 𝗯𝘆 𝗡𝗵𝗮 𝗔𝗻 𝗣𝗮 𝗧𝗲

[MITM]
hostname = %APPEND% spclient.wg.spotify.com

[Script]
spotify-json = type=http-request,pattern=^https:\/\/spclient\.wg\.spotify\.com\/(artistview\/v1\/artist|album-entity-view\/v2\/album)\/,requires-body=0,script-path=https://raw.githubusercontent.com/nhaanpate/javascript/nhaanpate/spotify-json.js

spotify-proto = type=http-response,pattern=^https:\/\/spclient\.wg\.spotify\.com\/(bootstrap\/v1\/bootstrap|user-customization-service\/v1\/customize)$,requires-body=1,binary-mode=1,script-path=https://raw.githubusercontent.com/nhaanpate/javascript/nhaanpate/spotify-proto.js
